version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysite.db
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  web:
    container_name: django
    build: ./dockerfiles/django_docker
    command: 
      uwsgi --socket :8000 --http :8001  --module mysite.wsgi --py-autoreload 1 -b 32768
    volumes:
      - ./django:/code
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    container_name: nuxt
    build: ./dockerfiles/nuxt_docker 
    tty: true
    # command: >
    #   /bin/bash -c 'cd front && yarn dev'
    volumes:
      - ./nuxt:/code
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web

volumes:
  mysqldata: